### PR TITLE
userSchema added jwt implemented

### PR DESCRIPTION
**Pull request by shradiphylleia**
resolves: #10 #14

### CODE REVIEW

**Comment by Vaibhav-Rawat03** [comment]
Is the frontend using vite?

**Comment by Vaibhav-Rawat03** [comment]
Also it seems you have done a lot of work 
please specify what all yu have done so i can assign you the points

**Comment by shradiphylleia** [comment]
the frontend part is not implemented by me. While I was working a PR was merged which had the app.js where I have done minor fixes:- res.render('homepage") along with /login /signup and their respective get and post method backend.
also added user schema in the models/user file. This PR resolves #10  #14  along with setting up logout and cookie session using cookie-parser. the only thing is it all has been added to the folder structure which was merged before-did this to maintain the structure.Please let me know if any other changes are required from my end.

**Comment by Vaibhav-Rawat03** [comment]
Remove everthing that you have not done please

**Comment by Vaibhav-Rawat03** [comment]
please also updated your fork and then make a new pull request(PR)

**Comment by shradiphylleia** [comment]
will create a new PR. should i create a new app.js and package.json

**Comment by Vaibhav-Rawat03** [comment]
Its up to you just make sure it does not have any merge conflicts and make sure the branch has your name

**Pull request closed without merging**
