### PR TITLE
Fixes #1: Created home page with navigation links to login and register pages

### LINKED ISSUE #1: Setup Home Page
Create a basic home page with navigation links to login and register pages.

### PR DESCRIPTION
**Pull request by ParthDhavan04**
Created home page with navigation links to login and register pages

### CODE REVIEW

**Comment by Vaibhav-Rawat03** [comment]
kidly a .gitignore file and add the node modules folder in it.
node modules folder is not supposed to be pushed

**Comment by ParthDhavan04** [comment]
Okay! I am on it.

**Comment by ParthDhavan04** [comment]
I have added it in git ignore and removed the modules.Please check.

**Comment by Vaibhav-Rawat03** [comment]
Kindly put the app.js file inside the frontend folder

**Comment by ParthDhavan04** [comment]
This app.js file is for the Backend. I have added a separate App.js file in frontend folder in src.

**Comment by Vaibhav-Rawat03** [comment]
Also put the package file and package lock file inside the frontend folder

**Comment by Vaibhav-Rawat03** [comment]
only the frontend and the backend folder will be visible in the repo and inside them al the work should be done
kindly check the discord for any confusion

**Pull request merged**
